<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MDB22LT506" name="com.ether.runner.CucumberTestRunner" tests="12" failures="0" timestamp="11 Jun 2020 08:27:22 GMT" time="607.478" errors="1">
  <testcase name="feature" time="19.725" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="18.791" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="58.482" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="52.424" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="135.535" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="26.057" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="46.045" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="12.540" classname="com.ether.runner.CucumberTestRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: null">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: null
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ether.steps.SampleTestLogin.verify_default_username_content_in_the_username_textbox(SampleTestLogin.java:91)
at âœ½.And verify default username content in the username textbox(RememberMe_vineeth.feature:13)
]]>
    </error>
  </testcase> <!-- feature -->
  <testcase name="feature" time="23.642" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="25.350" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="75.120" classname="com.ether.runner.CucumberTestRunner"/>
  <testcase name="feature" time="113.767" classname="com.ether.runner.CucumberTestRunner"/>
</testsuite> <!-- com.ether.runner.CucumberTestRunner -->
